name: Deploy Laravel to Azure Web App

env:
  PROJECT_PATH: /home/site/wwwroot/
  DATABASE_PATH: /home/site/wwwroot/storage/

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate environment file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Generate .htacces at project root
        run: echo "${{ env.AZURE_WEBAPP_ROOT_HTACCESS }}" > .htaccess

      - name: Install Node.js and build dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install && npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, intl, pdo_sqlite
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Laravel dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # - name: Create database file
      #   run: |
      #     touch ${{ env.DATABASE_PATH }}database.sqlite
      #     chmod -R 775 ${{ env.DATABASE_PATH }}

      - name: Run migrations
        run: |
          php artisan cache:table
          php artisan migrate:fresh --force
          php artisan db:seed --force

      - name: Verify Database Connection
        run: php artisan migrate:status

      - name: Clear Cache
        run: |
          php artisan cache:clear
          php artisan view:clear
          php artisan config:clear

      - name: Zip project for deployment
        run: zip -r release.zip . -x "*.git*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
