name: Deploy Laravel to Azure Web App

env:
  AZURE_NGINX_CONFIG: lanvender.conf
  DATABASE_PATH: database/

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate environment file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install Node.js and build dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install && npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, intl, pdo_sqlite
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Laravel dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          composer require fakerphp/faker --dev
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Configure Nginx for Laravel
        run: |
          echo "server {
            listen 8080;
            listen [::]:8080;
            server_name lanvender.azurewebsites.net www.lanvender.azurewebsites.net example.com www.example.com;
            root /home/site/wwwroot/public;
            index index.php index.html index.htm;
            port_in_redirect off;

            location / {
                try_files \$uri \$uri/ /index.php?\$query_string;
            }

            # Disable .git directory
            location ~ /\.git {
                deny all;
                access_log off;
                log_not_found off;
            }

            location ~ \.php\$ {
                fastcgi_split_path_info ^(.+?\.[Pp][Hh][Pp])(|/.*)$;
                fastcgi_pass 127.0.0.1:9000;
                include fastcgi_params;
                fastcgi_param HTTP_PROXY "";
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param QUERY_STRING $query_string;
                fastcgi_intercept_errors on;
                fastcgi_connect_timeout         300;
                fastcgi_send_timeout           3600;
                fastcgi_read_timeout           3600;
                fastcgi_buffer_size 128k;
                fastcgi_buffers 4 256k;
                fastcgi_busy_buffers_size 256k;
                fastcgi_temp_file_write_size 256k;
            }
          }" | sudo tee ${{ env.AZURE_NGINX_CONFIG }}

      - name: Run migrations
        run: |
          touch ${{ env.DATABASE_PATH }}database.sqlite
          chmod -R 775 ${{ env.DATABASE_PATH }}
          php artisan cache:table
          composer dump-autoload
          php artisan migrate:fresh --force
          php artisan db:seed --force
          php artisan migrate:status

      - name: Clear Cache
        run: |
          php artisan cache:clear
          php artisan view:clear
          php artisan config:clear

      - name: Zip project for deployment
        run: zip -r release.zip . -x "*.git*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
