name: Deploy Laravel to Azure Web App

env:
  PROJECT_PATH: /home/site/wwwroot/

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate environment file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Validate .env file
        run: cat .env

      - name: Install Node.js and build dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install && npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, intl, pdo_sqlite
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Laravel dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          php ${{ env.PROJECT_PATH }}artisan key:generate
          php ${{ env.PROJECT_PATH }}artisan config:cache
          php ${{ env.PROJECT_PATH }}artisan route:cache
          php ${{ env.PROJECT_PATH }}artisan view:cache

      - name: Run migrations
        run: |
          php ${{ env.PROJECT_PATH }}artisan cache:table
          php ${{ env.PROJECT_PATH }}artisan migrate --force

      - name: Verify Database Connection
        run: php ${{ env.PROJECT_PATH }}artisan migrate:status

      - name: Clear Cache
        run: |
          php ${{ env.PROJECT_PATH }}artisan cache:clear
          php ${{ env.PROJECT_PATH }}artisan view:clear
          php ${{ env.PROJECT_PATH }}artisan config:clear

      - name: Zip project for deployment
        run: zip -r release.zip . -x "*.git*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip

      - name: Database directory permission changes
        run: chmod -R 775 ${{ env.PROJECT_PATH }}database

      - name: Check Azure Web App Logs
        run: az webapp log tail --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_WEBAPP_RESOURCE_GROUP }}

      - name: Restart Azure Web App
        run: az webapp restart --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_WEBAPP_RESOURCE_GROUP }}
