name: Deploy Laravel to Azure Web App

env:
  APP_HOST: lanvender.azurewebsites.net
  DATABASE_PATH: database/

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate environment file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install Node.js and build dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install && npm run build

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, intl, pdo_sqlite
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Laravel dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          composer require fakerphp/faker --dev
          php artisan key:generate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Configure Nginx for Laravel
        run: |
          echo "server {
            listen 80;
            server_name _;
            root /home/site/wwwroot/public;
            index index.php index.html index.htm;

            location / {
                try_files \$uri \$uri/ /index.php?\$query_string;
            }

            location ~ \.php\$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
                fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
                include fastcgi_params;
            }
          }" | sudo tee /etc/nginx/sites-available/${{ env.APP_HOST }}

      - name: Enable Nginx Configuration
        run: |
          sudo ln -s /etc/nginx/sites-available/${{ env.APP_HOST }} /etc/nginx/sites-enabled/
          sudo systemctl restart nginx

      - name: Run migrations
        run: |
          touch ${{ env.DATABASE_PATH }}database.sqlite
          chmod -R 775 ${{ env.DATABASE_PATH }}
          php artisan cache:table
          composer dump-autoload
          php artisan migrate:fresh --force
          php artisan db:seed --force
          php artisan migrate:status

      - name: Clear Cache
        run: |
          php artisan cache:clear
          php artisan view:clear
          php artisan config:clear

      - name: Zip project for deployment
        run: zip -r release.zip . -x "*.git*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
